---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.name" . }}-server-config
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    service: server
data:
  config.yaml: |
    {{- pick .Values.config "server" "oidc" "db" "psql" "crdb" "spicedb" "tracing" "events" | toYaml | nindent 4 }}
