apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    service: server
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.deployment.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.serverReplicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      service: server
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        service: server
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- with .Values.deployment.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PERMISSIONSAPI_SERVER_LISTEN
              value: ":{{ include "permapi.listenPort" . }}"
            - name: PERMISSIONSAPI_SERVER_SHUTDOWN_GRACE_PERIOD
              value: "{{ .Values.config.server.shutdownGracePeriod }}"
          {{- with .Values.config.server.trustedProxies }}
            - name: PERMISSIONSAPI_SERVER_TRUSTED_PROXIES
              value: "{{ join " " . }}"
          {{- end }}
          {{- if .Values.config.oidc.issuer }}
          {{- with .Values.config.oidc.audience }}
            - name: PERMISSIONSAPI_OIDC_AUDIENCE
              value: "{{ . }}"
          {{- end }}
          {{- with .Values.config.oidc.issuer }}
            - name: PERMISSIONSAPI_OIDC_ISSUER
              value: "{{ . }}"
          {{- end }}
          {{- with .Values.config.oidc.refreshTimeout }}
            - name: PERMISSIONSAPI_OIDC_REFRESH_TIMEOUT
              value: "{{ . }}"
          {{- end }}
          {{- end }}
            - name: PERMISSIONSAPI_SPICEDB_ENDPOINT
              value: "{{ .Values.config.spicedb.endpoint }}"
            - name: PERMISSIONSAPI_SPICEDB_INSECURE
              value: "{{ .Values.config.spicedb.insecure }}"
            - name: PERMISSIONSAPI_SPICEDB_VERIFYCA
              value: "{{ .Values.config.spicedb.verifyCA }}"
          {{- if .Values.config.spicedb.policyConfigMapName }}
            - name: PERMISSIONSAPI_SPICEDB_POLICYFILE
              value: /policy/policy.yaml
          {{- end }}
            - name: PERMISSIONSAPI_TRACING_ENABLED
              value: "{{ .Values.config.tracing.enabled }}"
            - name: PERMISSIONSAPI_TRACING_PROVIDER
              value: "{{ .Values.config.tracing.provider }}"
            - name: PERMISSIONSAPI_TRACING_ENVIRONMENT
              value: "{{ .Values.config.tracing.environment }}"
            {{- if .Values.config.spicedb.caSecretName }}
            - name: SSL_CERT_DIR
              value: "/etc/ssl/spicedb"
            {{- end }}
            {{- if eq .Values.config.tracing.provider "jaeger" }}
            - name: PERMISSIONSAPI_TRACING_JAEGER_ENDPOINT
              value: "{{ .Values.config.tracing.jaeger.endpoint }}"
            - name: PERMISSIONSAPI_TRACING_JAEGER_USER
              value: "{{ .Values.config.tracing.jaeger.user }}"
            - name: PERMISSIONSAPI_TRACING_JAEGER_PASSWORD
              value: "{{ .Values.config.tracing.jaeger.password }}"
            {{- end }}
            {{- if eq .Values.config.tracing.provider "otlp" }}
            - name: PERMISSIONSAPI_TRACING_OTLP_ENDPOINT
              value: "{{ .Values.config.tracing.otlp.endpoint }}"
            - name: PERMISSIONSAPI_TRACING_OTLP_INSECURE
              value: "{{ .Values.config.tracing.otlp.insecure }}"
            - name: PERMISSIONSAPI_TRACING_OTLP_CERTIFICATE
              value: "{{ .Values.config.tracing.otlp.certificate }}"
            {{- end }}
          envFrom:
            - secretRef:
                name: "{{ .Values.config.spicedb.pskSecretName }}"
          ports:
            - name: http
              containerPort: {{ include "permapi.listenPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: {{ include "permapi.server.volumeMounts" . | nindent 12 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes: {{ include "permapi.server.volumes" . | nindent 8 }}
