apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    service: worker
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.deployment.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.workerReplicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      service: worker
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        service: worker
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- with .Values.deployment.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - worker
            - --config
            - /config/config.yaml
          env:
            - name: PERMISSIONSAPI_SERVER_LISTEN
              value: ":{{ include "permapi.listenPort" . }}"
          {{- if .Values.config.events.nats.tokenSecretName }}
            - name: PERMISSIONSAPI_EVENTS_NATS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.events.nats.tokenSecretName }}
                  key: token
          {{- end }}
          {{- if .Values.config.spicedb.policyConfigMapName }}
            - name: PERMISSIONSAPI_SPICEDB_POLICYFILE
              value: /policy/policy.yaml
          {{- end }}
            {{- if .Values.config.spicedb.caSecretName }}
            - name: SSL_CERT_DIR
              value: "/etc/ssl/spicedb"
            {{- end }}
          envFrom:
            - secretRef:
                name: "{{ .Values.config.spicedb.pskSecretName }}"
          ports:
            - name: http
              containerPort: {{ include "permapi.listenPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: {{ include "permapi.worker.volumeMounts" . | nindent 12 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes: {{ include "permapi.worker.volumes" . | nindent 8 }}
