name: Lint - Helm
on:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  helm-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5

      - name: Run helm lint
        run: helm lint chart/permissions-api
