name: Trivy Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  image-scan:
    name: image-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.metadata.outputs.tags }}
          scanners: 'vuln,secret'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'table'
          exit-code: '1'

  repo-scan:
    name: repo-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Scan repo
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,secret'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'table'
          exit-code: '1'
